### ISSUE TITLE
[perception] Détection de l'objet pas suffisamment précise pour aggriper l'objet

### ISSUE THREAD

**Issue by olivier-stasse** [aip-primeca-occitanie/projet-integration-sri-2022-2023#16]

**Comment by olivier-stasse** [comment]
Il semblerait qu'il y ait un problème le long de l'axe de détection du markeur.
Probablement un problème d'échelle.
Le marqueur est-il à la bonne taille ?

**Comment by AlexLtte** [comment]
Le changement de taille du marqueur a réglé le problème d'estimation de la pose de l'objet.
